### PR TITLE
Deals with Issue #61, one line code change fix to a test (latter in second commit)

### PR DESCRIPTION
**Pull request by 18AdrianoH**
Deals with Issue #61 
(https://github.com/aws/aws-encryption-sdk-python/issues/61)

Fixes the sphinx linking issue on readthedocs.  Also makes a small fix to a buggy test.  Read the second commit message for details on this.

A lot of seeming change is just python black reformatting the code to look as it should.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

No files were moved, added, or removed.  Just edited.

### CODE REVIEW

**Comment by 18AdrianoH** [comment]
Also it looks like appveyor doesn't like some stuff not sure if it's me or the issue we found before?

**Comment by mattsb42-aws** [comment]
Appveyor is a known issue #159.

Please run `tox -re autoformat` over this. There are a variety of formatting changes that do not fit our requirements.

**Comment by mattsb42-aws** [comment]
`tox -re lint` will also catch all of the other linters as well, if you want to check them locally before waiting on the CI.

**Comment by 18AdrianoH** [comment]
Made the formatting changes.  flake8 and pylint pass now for me locally, so I believe it should be ok.

**Comment by 18AdrianoH** [comment]
Please go to PR #187 which is reset to correct commit.

**Pull request closed without merging**
